port: 3000
encoding: UTF-8
title: jr-cologne.de
email: kontakt@jr-cologne.de
description: Meine persönliche Website
baseurl: ""
url: "https://jr-cologne.de"
twitter_username: jrcologne
github_username: jr-cologne
codepen_username: jr-cologne

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - _app
  - README.md
  - design
keep_files:
  - _app
  - kontakt.php
  - sitemap.xml

gems:
  - jekyll-sitemap
