port: 3000
encoding: UTF-8
title: jr-cologne.de
email: kontakt@jr-cologne.de
description: Du bist ebenfalls ein kleiner Web-Fanatiker und liebst es, Webseiten zu designen sowie zu entwickeln? Dann bist du bei mir genau richtig!
keywords: webentwicklung,webdesign,javascript,cms,mysql,php,php7,sql,css,css3,jquery,html5,ide,content management system,programmieren,sass,js,ux design,ui,ux,ui design,php programmierung,webseiten erstellen,web,editor,internet,css tutorial,css3 tutorial,html tutorial,html5 tutorial,javascript tutorial,js tutorial,php tutorial,sql tutorial,tutorials
baseurl: ""
url: "https://jr-cologne.de"
twitter_username: jrcologne
github_username: jr-cologne
codepen_username: jr-cologne

cloudinary_article-image: https://res.cloudinary.com/jr-cologne-de/image/upload/t_article-image/
cloudinary_content-image: https://res.cloudinary.com/jr-cologne-de/image/upload/t_content-image/
cloudinary_content-image-large: https://res.cloudinary.com/jr-cologne-de/image/upload/t_content-image-large/

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - _app
  - README.md
  - CHANGELOG.md
  - DESIGN.md
  - design
  - composer.json
keep_files:
  - _app
  - kontakt.php
  - sitemap.xml
  - node_modules

plugins:
  - jekyll-sitemap

future: true
