port: 3000
encoding: UTF-8
title: jr-cologne.de
email: kontakt@jr-cologne.de
tel: 004915738408326
tel_human: +49 (0)1573 84 08 326
description: Du bist ebenfalls ein großer Tech-Enthusiast und liebst es, Webseiten zu designen sowie zu entwickeln? Dann bist du bei mir genau richtig!
keywords: webentwicklung,webdesign,javascript,cms,mysql,php,php7,sql,css,css3,jquery,html5,ide,content management system,programmieren,sass,js,ux design,ui,ux,ui design,php programmierung,webseiten erstellen,web,editor,internet,css tutorial,css3 tutorial,html tutorial,html5 tutorial,javascript tutorial,js tutorial,php tutorial,sql tutorial,tutorials
baseurl: ""
url: "https://jr-cologne.de"
twitter_username: jrcologne
github_username: jr-cologne
codepen_username: jr-cologne
theme-color: "#29353b"
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules
  - _app
  - README.md
  - LICENSE
  - composer.json
  - resources/article-components.html
keep_files:
  - _app
  - sitemap.xml
  - node_modules

plugins:
  - jekyll-sitemap

future: true
